services:
  - type: worker
    name: rashid-help-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: DEVELOPER_CONTACT
        value: "@Rashid_1Help"
      - key: DATABASE_PATH
        value: /opt/render/project/src/rashid_help.db
